### PR TITLE
Fixup README

### PR DESCRIPTION
**Pull request by Foggalong**
Noticed when importing this project into one of my own that the README was triggering a bunch of code quality warnings. This PR doesn't change any of the content of the README, it just fixes all those minor issues like trailing spaces, codeblocks without a specified syntax language, spacing in lists, etc.

### CODE REVIEW

**Comment by Foggalong** [comment]
Latest commit removes metube, service which like Mixer is now defunct

Screenshot from 2021-09-21 14-35-29

(to get to that website I had to accept so many invlaid SSL certificates)

**Comment by Foggalong** [comment]
Final commit performs the same kind of fixes to the example, here it's mainly duplicate H1s and tailing spaces (though there was the information for Mixer still left in the separate example file)

**Comment by nathancy** [comment]
Hi! Thanks for your contribution. The first three commits look good but the `Perform MD fixes to example` commit will break the Twitch section. It removes the required domain parameter. If you remove that entire last commit I can merge it in. I'll then manually remove the extra Mixer and metube references

**Comment by nathancy** [comment]
Actually just put back the `twitchDomain` line, remove the `title: "Full Example"` in `example.md` and `README.md`, and remove `mixerId: putYourIDHere`. Otherwise it looks good

**Comment by Foggalong** [comment]
Thanks! Not sure why the Twitch line got removed, definitely in error

**Pull request merged**
